---
- apt: name=quagga
- template: dest=/etc/quagga/ src=daemons backup=yes
  notify: restart quagga
- copy: dest='/etc/quagga/{{ item }}.conf' mode=644 owner=quagga group=quagga content="" force=no
  with_items: '{{ quagga_daemons }}'
  notify: restart quagga

