---
- import_tasks: load-variables.yml
  tags: nrpeconf

- name: nrpe_plugin_dir_default
  set_fact:
    nrpe_plugin_dir: /usr/lib/nagios/plugins
  tags: nrpeconf

- name: nrpe_plugin_dir_1
  set_fact:
    nrpe_plugin_dir: /usr/lib64/nagios/plugins
  when: ansible_os_family == "RedHat" and ansible_architecture != "i686"
  tags: nrpeconf

- name: install epel repo
  yum:
    name: "{{ epel_repo_url }}"
    state: present
  tags: epel
  when: ansible_os_family == 'RedHat'

- name: import epel gpg key
  rpm_key:
    key: "{{ epel_repo_gpg_key_path }}"
    state: present
  tags: epel
  when: ansible_os_family == 'RedHat'

- name: Install NRPE
  package: >
    name={{ nrpe_package_name }}
    state=latest

- name: Install Plugins
  package : >
    name={{ item }}
    state=latest
  when: ansible_os_family == 'RedHat'
  with_items:
   - nagios-plugins-all

- name: Enable NRPE service
  service: >
    name={{ nrpe_service_name }}
    state=started
    enabled=yes

- name: Install check_mem plugin
  copy: src=files/check_mem dest={{ nrpe_plugin_dir }}/check_mem mode=755
  tags: nrpeconf

- name: Install check_ospf plugin
  copy: src=check_ospf dest={{ nrpe_plugin_dir }}/ mode=755
  tags: nrpeconf

- name: NRPE config file
  template: src=nrpe.cfg dest=/etc/nagios/nrpe.cfg
  notify: restart nrpe
  tags: nrpeconf

#for redhat
- name: nrpe.d dir
  file: path={{ nrpe_conf_dir }}/nrpe.d state=directory

- name: NRPE checks
  template: > 
    src=nrpe_check.cfg
    dest={{ nrpe_conf_dir }}/nrpe.d/{{ item.key }}.cfg
  with_dict: "{{ nrpe_checks }}"
  notify: restart nrpe
  tags: nrpeconf

- block:
  - copy: src=check_asterisk.cfg dest=/etc/nagios/nrpe.d/
  - copy: src=check_asterisk.sh dest=/etc/asterisk/
  - template: src=sudoers.d/nrpe_asterisk dest=/etc/sudoers.d/ mode=0440
  when: "'asterisk_servers' in group_names"

