---
- name: include client
  import_tasks: client.yml 
  when:
  - run_nagios_client is defined 
  - run_nagios_client == true

- name: include server
  import_tasks: server.yml 
  when: run_nagios_server is defined 

