---
- name: Stop and disable the dhcp services DHCP
  service: name={{ dhcp_service }} state=stopped enabled=no 

- name: Uninstall the required  packages in Redhat derivatives
  yum: name={{ dhcp_server_package }} state=absent
  when: ansible_os_family == 'RedHat'

- name: Uninstall the required packages in Debian derivatives
  apt: name={{ dhcp_server_package }} state=absent purge=yes
  when: ansible_os_family == 'Debian'

- name: Uninstall the required packages in ArchLinux derivatives
  pacman: name={{ dhcp_server_package }} state=absent
  when: ansible_os_family == 'Archlinux'

- name: Remove dhcp_server_config_local file
  file: dest={{ dhcp_server_config_local }} state=absent

- name: Uninstall done
  fail: msg="Uninstall done"
