---
- hosts: all
  roles:
  - { role: backup, ansible_become: no, tags: backup, src: [/etc/network/interfaces, /etc/fstab] }
- hosts: bind_servers
  roles:
  - { role: backup, ansible_become: no, tags: backup, src: [/etc/bind/named.conf.local] }
- hosts: quagga_servers
  roles:
  - { role: backup, ansible_become: no, tags: backup, src: [/etc/quagga] }
- hosts: fw_servers
  roles:
  - { role: backup, ansible_become: no, tags: backup, src: [/etc/network/fw] }
- hosts: asterisk_servers
  roles:
  - { role: backup, ansible_become: no, tags: backup, src: [/etc/asterisk] }
- hosts: kvm_servers
  roles:
  - { role: backup, ansible_become: no, tags: backup, src: [/etc/libvirt] }
- hosts: mail_servers
  roles:
  - { role: backup, ansible_become: no, tags: backup, src: [/etc/postfix] }
