---
- hosts: kvm_servers
  vars:
    - name: newguestname

  tasks:
    - virt: name="{{ name }}" state=destroyed
      ignore_errors: True
    - virt: name="{{ name }}" command=undefine
      ignore_errors: True
    - mount: src=/dev/vg0/"{{ name }}" fstype=auto name=/mnt/"{{ name }}" state=unmounted
    - mount: src=/dev/vg0/"{{ name }}" fstype=auto name=/mnt/"{{ name }}" state=absent
    - lvol: vg='vg0' lv='{{ name }}' state=absent force=yes
