---
- hosts: kvm_servers
  vars:
  - ansible_become: true
  - name: newguestname
  - vg: vg0

  tasks:
  - block:
    - virt: name="{{ name }}" state=destroyed
    - virt: name="{{ name }}" command=undefine
      tags: undefine
    - mount: name="/mnt/{{ name }}" state=unmounted
    - mount: name="/mnt/{{ name }}" state=absent
    - shell: kpartx -d /dev/mapper/{{ vg }}-{{ name }}
    - lvol: vg='{{ vg }}' lv='{{ name }}' state=absent force=yes
    ignore_errors: True

