---
- hosts: kvm_servers
  vars:
    - ansible_become: true
    - name: newguestname

  tasks:
    - virt: name="{{ name }}" state=destroyed
      ignore_errors: True
    - virt: name="{{ name }}" command=undefine
      ignore_errors: True
    - mount: name="/mnt/{{ name }}" state=unmounted
    - mount: name="/mnt/{{ name }}" state=absent
    - lvol: vg='vg0' lv='{{ name }}' state=absent force=yes
