---
- hosts: all
  environment: '{{ custom_env | default("{}") }}'
  roles:
  - { role: common, tags: common }

- hosts: bind_servers
  environment: '{{ custom_env | default("{}") }}'
  roles:
  - { role: bind, tags: bind }

- hosts: dhcp_servers
  environment: '{{ custom_env | default("{}") }}'
  roles:
  - { role: 'dhcp_server', tags: dhcp }

- hosts: vmware_guests
  environment: '{{ custom_env | default("{}") }}'
  tasks:
  - apt: pkg=open-vm-tools
    tags: vm

- hosts: atftp_servers
  environment: '{{ custom_env | default("{}") }}'
  roles:
  - { role: atftpd, tags: atftp }

- hosts: nfs_servers
  environment: '{{ custom_env | default("{}") }}'
  roles:
  - { role: nfs_server, tags: nfs }

- hosts: moinmoin_servers
  environment: '{{ custom_env | default("{}") }}'
  roles:
  - { role: moinmoin, tags: moin }

- hosts: trac_servers
  environment: '{{ custom_env | default("{}") }}'
  roles:
  - { role: trac, tags: trac }

- hosts: quagga_servers
  environment: '{{ custom_env | default("{}") }}'
  roles:
  - { role: backup, ansible_sudo: no, tags: backup, src: [/etc/quagga] }

- hosts: fw_servers
  environment: '{{ custom_env | default("{}") }}'
  roles:
  - { role: backup, ansible_sudo: no, tags: backup, src: [/etc/network/fw] }

- hosts: asterisk_servers
  environment: '{{ custom_env | default("{}") }}'
  roles:
  - { role: backup, ansible_sudo: no, tags: backup, src: [/etc/asterisk] }

- hosts: libvirt_servers
  environment: '{{ custom_env | default("{}") }}'
  roles:
  - { role: backup, ansible_sudo: no, tags: backup, src: [/etc/libvirt] }

- hosts: ftp_servers
  environment: '{{ custom_env | default("{}") }}'
  roles:
  - { role: proftpd, tags: ftp }

- hosts: mysql_servers
  environment: '{{ custom_env | default("{}") }}'
  roles:
  - { role: mysql, tags: mysql }

- hosts: megaraid_servers
  environment: '{{ custom_env | default("{}") }}'
  roles:
  - { role: megaraid, tags: megaraid }

