---
- hosts: all
  environment: '{{ custom_env | default("{}") }}'
  roles:
  - { role: common, tags: common }

- hosts: bind_servers
  environment: '{{ custom_env | default("{}") }}'
  roles:
  - { role: bind, tags: bind }

- hosts: dhcp_servers
  environment: '{{ custom_env | default("{}") }}'
  roles:
  - { role: 'dhcp_server', tags: dhcp }

- hosts: vmware_guests
  environment: '{{ custom_env | default("{}") }}'
  tasks:
  - apt: pkg=open-vm-tools
    tags: vm

- hosts: tftp_servers
  environment: '{{ custom_env | default("{}") }}'
  roles:
  - { role: atftpd, tags: tftp }

- hosts: nfs_servers
  environment: '{{ custom_env | default("{}") }}'
  roles:
  - { role: nfs_server, tags: nfs }

- hosts: moinmoin_servers
  environment: '{{ custom_env | default("{}") }}'
  roles:
  - { role: moinmoin, tags: moin }

- hosts: trac_servers
  environment: '{{ custom_env | default("{}") }}'
  roles:
  - { role: trac, tags: trac }

- hosts: ftp_servers
  environment: '{{ custom_env | default("{}") }}'
  roles:
  - { role: proftpd, tags: ftp }

- hosts: mysql_servers
  environment: '{{ custom_env | default("{}") }}'
  roles:
  - { role: mysql, tags: mysql }

- hosts: cacti_servers
  environment: '{{ custom_env | default("{}") }}'
  roles:
  - { role: cacti, tags: cacti }


- hosts: megaraid_servers
  environment: '{{ custom_env | default("{}") }}'
  roles:
  - { role: megaraid, tags: megaraid }

- hosts: workstations
  environment: '{{ custom_env | default("{}") }}'
  roles:
  - { role: workstation, tags: workstation }

- hosts: kvm_servers
  environment: '{{ custom_env | default("{}") }}'
  roles:
  - { role: kvm, tags: kvm }

- hosts: debootstrap_servers
  environment: '{{ custom_env | default("{}") }}'
  roles:
  - { role: debootstrap, tags: debootstrap }

- hosts: mail_servers
  environment: '{{ custom_env | default("{}") }}'
  roles:
  - { role: mail_server, tags: mail}
- hosts: squid_servers
  environment: '{{ custom_env | default("{}") }}'
  roles:
  - { role: squid, tags: squid}

- hosts: monitoring-servers
  environment: '{{ custom_env | default("{}") }}'
  roles:
  - { role: 'sdarwin.nagios', tags: nagios}

