---
lang: en_US.UTF-8
timezone: Europe/Moscow
common_root_alias: 'root@{{ domain }}'
common_sysctl:
  net.ipv6.conf.all.disable_ipv6: 1
ssh_listen_port: 22
ssh_default_port: '{{ ssh_listen_port }}'
  
# list of modules to add into /etc/modules-load.d/90-ansible-common.conf
common_modules_load:
common_modprobe_conf:
preffered_mirror: 'http://mirror.yandex.ru'
install_pkgs_distribution:
install_pkgs_inventory_group:
install_pkgs_inventory_host:
install_pkgs:
- apg
- bc
- cryptsetup
- curl
- dos2unix
- dosfstools
- e2fsprogs
- ethtool
- file
- findutils
- ftp
- gzip
- iftop
- iotop
- iproute
- iptables
- less
- lsof
- lvm2
- mc
- mdadm
- nano
- ngrep
- nmap
- ntp
- ntpdate
- openssh-server
- p7zip
- pciutils
- postfix
- psmisc
- python-httplib2
- python-simplejson
- rsync
- screen
- sdparm
- sed
- strace
- sudo
- sysstat
- tar
- tcpdump
- telnet
- traceroute
- unzip
- vim
- wget
- whois

