---
lang: en_US.UTF-8
timezone: Europe/Moscow
preffered_mirror: 'http://mirror.yandex.ru'
ssh_listen_port: '{{ ansible_ssh_port | d("22") }}'
ssh_default_port: '{{ ssh_listen_port }}'

common_root_alias: 'root@{{ domain }}'

common_sysctl:
  net.ipv6.conf.all.disable_ipv6: 1

common_grub_defaults:
  GRUB_CMDLINE_LINUX_DEFAULT: 'console=tty {{ common_cmdline_append | d() }}'

# list of modules to add into /etc/modules-load.d/90-ansible-common.conf
common_modules_load:

common_sudoers_rules:
- '%admin ALL = NOPASSWD:/usr/sbin/tcpdump, /usr/sbin/iftop'

common_modprobe_conf:
- 'blacklist floppy'

common_install_pkgs_distribution: '[]'
common_install_pkgs_inventory_group: '[]'
common_install_pkgs_inventory_host: '[]'
common_install_pkgs:
- apg
- bc
- cryptsetup
- curl
- dbus
- dos2unix
- dosfstools
- e2fsprogs
- ethtool
- file
- findutils
- ftp
- gzip
- htop
- iftop
- iotop
- iproute
- iptables
- less
- lsof
- lvm2
- mc
- mdadm
- nano
- ngrep
- nmap
- ntpdate
- openssh-server
- p7zip
- pciutils
- postfix
- psmisc
- python-httplib2
- python-simplejson
- rsync
- screen
- sdparm
- sed
- strace
- sudo
- sysstat
- tar
- tcpdump
- telnet
- tmux
- traceroute
- unzip
- vim
- wget
- whois
- xfsprogs

