---
lang: en_US.UTF-8
timezone: Europe/Moscow
common_root_alias: 'root@{{ domain }}'
common_sysctl:
  net.ipv6.conf.all.disable_ipv6: 1
install_pkgs:
- apg
- aptitude
- atftp
- bsd-mailx
- cryptsetup
- curl
- dnsutils
- dos2unix
- dosfstools
- e2fsprogs
- ecryptfs-utils
- ethtool
- file
- findutils
- ftp
- gzip
- iftop
- iotop
- ipcalc
- iproute
- iptables
- iputils-arping
- iputils-ping
- iputils-tracepath
- isc-dhcp-client
- less
- locales
- lsb-release
- lsof
- lvm2
- makedev
- mc
- mdadm
- mount
- nano
- ngrep
- nmap
- ntp
- ntpdate
- openssh-server
- p7zip
- pciutils
- procps
- psmisc
- python-apt
- python-httplib2
- python-simplejson
- rsync
- screen
- sdparm
- sed
- sshfs
- strace
- sudo
- sysstat
- tar
- tcpdump
- telnet
- traceroute
- unzip
- vim
- wget
- whois
