---
- setup:
  when: ansible_os_family is not defined

- include_vars: '{{ item }}'
  with_first_found:
    - 'os_{{ ansible_os_family }}.yml'
    - os_default.yml

- apt: state=present name='{{ atftpd_install_pkgs }}'

- template: dest=/etc/default/atftpd src=atftpd
  notify: restart atftpd

- file: dest={{ tftp_root }}/pxelinux.cfg state=directory

- file: dest={{ tftp_root }}/{{ item | basename }} src='{{ item }}' state=link force=yes
  with_items: '{{ pxe_files }}'

- template: dest={{ tftp_root }}/pxelinux.cfg/default src=pxelinux.cfg force=yes backup=yes

- name: Stop inetd service
  service: name="{{ inetd_service_name }}" state=stopped
  ignore_errors: True

- name: Disable inetd service
  service: name="{{ inetd_service_name }}" enabled=no
  ignore_errors: True

- name: Start the atftpd service
  service: name=atftpd state=started

- name: Enable the atftpd service
  service: name=atftpd enabled=yes

- import_tasks: centos-install.yml
  when: centos_install_srv
  tags: centosinstall

- file: mode=a+rX dest={{ tftp_root }}/ recurse=yes

#- lineinfile: line='MODULES=netboot' regexp='^MODULES.*'
#- shell: update-initramfs -b {{ tftp_root }}/ -c -k "{{ ansible_kernel }}" -v
#  register: result
#- debug: var=result
#- synchronize: dest='{{ tftp_root }}/vmlinuz-{{ ansible_kernel }}' src='/boot/vmlinuz-{{ ansible_kernel }}'
#- lineinfile: line='MODULES=most' regexp='^MODULES.*'
#- shell: update-initramfs -b {{ tftp_root }}/ -c -k "{{ ansible_kernel }}" -v

