---
- setup:
  when: ansible_distribution is not defined

- include_vars: '{{ item }}'
  with_first_found:
    - 'os_{{ ansible_distribution }}.yml'
    - os_default.yml

- apt: state=installed name='{{ item }}'
  with_items: '{{ atftpd_install_pkgs }}'

- template: dest=/etc/default/atftpd src=atftpd
  notify: restart atftpd

- file: dest={{ tftp_root }}/pxelinux.cfg state=directory

- file: dest={{ tftp_root }}/{{ item | basename }} src='{{ item }}' state=link force=yes
  with_items: '{{ pxe_files }}'

- template: dest={{ tftp_root }}/pxelinux.cfg/default src=pxelinux.cfg force=yes backup=yes

- file: mode=a+rX dest={{ tftp_root }}/ recurse=yes

- name: Stop inetutils-inetd service
  service: name=inetutils-inetd state=stopped

- name: Disable inetutils-inetd service
  service: name=inetutils-inetd enabled=no

- name: Start the atftpd service
  service: name=atftpd state=started

- name: Enable the atftpd service
  service: name=atftpd enabled=yes

- include: centos-install.yml
  when: centos.ver is defined
  tags: centosinstall

#- lineinfile: line='MODULES=netboot' regexp='^MODULES.*'
#- shell: update-initramfs -b {{ tftp_root }}/ -c -k "{{ ansible_kernel }}" -v
#  register: result
#- debug: var=result
#- synchronize: dest='{{ tftp_root }}/vmlinuz-{{ ansible_kernel }}' src='/boot/vmlinuz-{{ ansible_kernel }}'
#- lineinfile: line='MODULES=most' regexp='^MODULES.*'
#- shell: update-initramfs -b {{ tftp_root }}/ -c -k "{{ ansible_kernel }}" -v

