---
mail_root: /var/mail
mail_server_name: '{{ inventory_hostname }}.{{ domain }}'
postfix_db_name: postfix
postfix_db_user: postfix
postfix_db_password: ChangeMe-CotDol3swo
postfix_main_cf:
  myhostname: '{{ mail_server_name }}'
  virtual_mailbox_base: '{{ mail_root }}'

roundcube_path: /opt/roundcube
roundcube_log_dir: /var/log/roundcube
roundcube_smtp_log: true
roundcube_log_logins: true
roundcube_log_session: false
roundcube_sql_debug: false
roundcube_imap_debug: false
roundcube_ldap_debug: false
roundcube_smtp_debug: false
roundcube_db_name: roundcube
roundcube_db_user: roundcube
roundcube_db_password: '{{ postfix_db_password }}'
roundcube_des_key_path: '{{ inventory_dir }}/credentials/{{ inventory_hostname }}/roundcube_des_key'

dovecot_db_user: dovecot
dovecot_db_password: '{{ postfix_db_password }}'
fail2ban_ignoreip: '127.0.0.1/8 192.168.0.0/16'

postfixadmin_allow:
- 10.0.0.0/8
- 192.168.0.0/16
