---
- name: Creating directory for host backup
  file: dest='{{ backup_dest }}/{{ inventory_hostname }}' state=directory
  delegate_to: localhost

- synchronize:
    src: '{{ item }}'
    dest: '{{ backup_dest }}/{{ inventory_hostname }}'
    delete: yes
    mode: pull
    copy_links: yes
    rsync_path: "sudo rsync"
    rsync_opts: '{{ backup_rsync_opts }}'
  with_items: '{{ backup_src }}'
  ignore_errors: True
