---
- name: Gather Facts
  setup:
  when: ansible_distribution is not defined

- name: Include Distribution version specific variables
  include_vars: "{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml"

- apt: pkg={{ item }} state=installed
  with_items: '{{ mysql_packages }}'

- template: dest=/etc/mysql/my.cnf src=my.cnf backup=yes
  notify: restart mysql

- template: dest=/etc/cron.d/mysqldump src=cronfile

- file: dest=/root/.my.cnf src=/etc/mysql/debian.cnf state=link
