---
- name: postmap sender_access
  shell: postmap /etc/postfix/sender_access

- name: postmap tls_per_site
  shell: postmap /etc/postfix/tls_per_site

- name: Generate mail alias database
  command: newaliases

- name: Check postfix and restart
  command: /usr/sbin/postfix -c /etc/postfix check
  notify: [ 'Restart postfix' ]

- name: Restart postfix
  service:
    name: 'postfix'
    state: 'restarted'

- name: Restart saslauthd
  service:
    name: 'saslauthd'
    state: 'restarted'

- name: Restart rsyslog
  service: name=rsyslog state=restarted

- name: Restart dovecot
  service: name=dovecot state=restarted
 
- name: Restart fail2ban
  service: name=fail2ban state=restarted

- name: Restart nginx
  service: name=nginx state=restarted
