---
- name: restart ssh
  service: name='{{ ssh_service_name }}' state=restarted

- name: restart snmpd
  service: name=snmpd state=restarted

- name: restart postfix
  service: name=postfix state=restarted

- name: newaliases
  shell: newaliases

- name: systemd reload
  shell: systemctl daemon-reload
  #systemd: daemon_reload=yes #new in ansible 2.2
 
- name: sysctl restart
  service: name=systemd-sysctl state=restarted

- name: update grub
  shell: update-grub

- name: enable serial console on ttyS0
  systemd: name=serial-getty@ttyS0 daemon_reload=yes enabled=yes state=started
