---
- name: Update repositories cache and install syslog-ng
  apt: name=syslog-ng update_cache=yes


- name: Creating directory for logs
  file: dest=/var/log/syslog-ng state=directory mode=0755

- name: Creating log file in /var/log/syslog-ng - syslog-ng.log
  copy: content="" dest=/var/log/syslog-ng/syslog-ng.log force=no owner=root group=root mode=0755
  
- name: Loading config file from template
  template: src=syslog-ng.conf.j2 dest=/etc/syslog-ng/syslog-ng.conf owner=root group=root mode=0755
  notify: restart syslog-ng

- name: Loading logrotate file from template
  template: src=syslog-ng.logrotate dest=/etc/logrotate.d/syslog-ng owner=root group=root mode=0755
  tags: this

- name: Enabling syslog-ng service
  systemd: name=syslog-ng enabled=yes daemon_reload=yes

- name: Starting syslog-ng service
  systemd: name=syslog-ng state=started
