---
- apt: state=present pkg=cacti
- apt: state=present pkg=cacti-spine
- apt: state=present pkg=snmp-mibs-downloader

- get_url: url='https://www.percona.com/downloads/percona-monitoring-plugins/1.1.5/percona-cacti-templates_1.1.5-1_all.deb' dest=./
- apt: deb='./percona-cacti-templates_1.1.5-1_all.deb'

- template: src=debian.php dest=/etc/cacti/debian.php
- template: src=spine.conf dest=/etc/cacti/spine.conf
- template: src=cron dest=/etc/cron.d/cacti
- template: src=apache2.conf dest=/etc/apache2/conf-available/cacti.conf
  notify: reload apache2
- file: src=../conf-available/cacti.conf dest=/etc/apache2/conf-enabled/cacti.conf state=link
  notify: reload apache2

- copy: src=get_tcp_connections dest=/usr/share/cacti/site/scripts/get_tcp_connections

- mysql_db: name=cacti

- mysql_user: name=cacti password='{{ cacti_db_password }}' priv='cacti.*:ALL'

- shell: mysql cacti < '{{ cacti_db_dump_path }}'
  when: restore is defined
