---
galaxy_info:
  author: René Moser
  company: Moser Systems
  license: MIT
  min_ansible_version: 1.4

  platforms:
  - name: Ubuntu
    versions:
    - all
  - name: Debian
    versions:
    - all
  categories:
  - system

dependencies:
- { role: backup, ansible_sudo: no, tags: backup, src: [/etc/bind/named.conf.local] }
