- name: Group Hosts by virtualization_type and virtualization_role
  group_by:
    key: virt_{{ ansible_virtualization_type }}_{{ ansible_virtualization_role }}
  tags: grubconfig

- name: Setup Grub Environment
  lineinfile: dest=/etc/default/grub line='{{ item.key }}="{{ item.value }}"' regexp='^{{ item.key }}=.*' create=no
  with_dict: "{{ common_grub_defaults }}"
  when: item.value != None
  notify: update grub
  tags: grubconfig

- name: Set Hostname
  hostname: name='{{inventory_hostname}}.{{domain}}'

- name: Edit /etc/hosts
  lineinfile: dest=/etc/hosts regexp='^127.0.1.1.*' line='127.0.1.1 {{inventory_hostname}}.{{domain}} {{inventory_hostname}}' insertafter='^127.0.0.1.*'

- name: Set Timezone
  file: dest=/etc/localtime src=/usr/share/zoneinfo/{{ timezone }} state=link force=yes

- name: Update resolv.conf
  template: dest=/etc/ src=resolv.conf
  when:
  - nameservers is defined
  - "'bind_servers' not in group_names"

- name: create locale gen file (bugfix)
  copy: dest=/etc/locale.gen content="{{ lang }} {{ lang.split('.')[1] }}\n"

- name: Install language-pack-en
  apt: name=language-pack-en
  when: ansible_os_family == "Ubuntu"

- name: create locale gen file (bugfix)
  copy: dest=/var/lib/locales/supported.d/ansible_common content="{{ lang }} {{ lang.split('.')[1] }}\n"
  when: ansible_os_family == "Ubuntu"

- name: Generate Locale
  locale_gen: name={{ lang }}

- name: Set Lang
  copy: dest='{{ lang_file }}' content='LANG="{{ lang }}"\n'

- name: Set Root Password
  user: name=root password="{{ root_password }}" update_password=always

- name: Setup Server Environment
  lineinfile: dest='/etc/environment' line='{{ item.key }}={{ item.value }}' regexp='{{ item.key }}=.*' create=yes
  with_dict: "{{ custom_env | default('{}') }}"
  when: item.value != None

- name: Set screenrc
  template: dest=/etc/screenrc src=screenrc

- template: dest=/etc/ src=tmux.conf
  tags: tmuxconf

- name: Vim Config Directory
  file: dest=/etc/vim/ state=directory

- name: Copy Vim Config
  template: src=vim/vimrc.local dest=/etc/vim/

- name: Copy Rsync Config
  template: src=rsyncd.conf dest=/etc/

- name: Copy /etc/sysctl.d/90-ansible-common.conf 
  template: dest=/etc/sysctl.d/ src=sysctl.d/90-ansible-common.conf
  notify: sysctl restart

- name: Copy /etc/modules-load.d/90-ansible-common.conf
  template: dest=/etc/modules-load.d/ src=modules-load.d/90-ansible-common.conf

- name: Copy /etc/modprobe.d/ansible-common.conf
  template: dest=/etc/modprobe.d/ src=modprobe.d/ansible-common.conf

