---
- block: 
  - name: Configure sources
    template: src='apt/sources.list.{{ ansible_distribution }}' dest=/etc/apt/sources.list backup=yes

  - name: APT Cache Update
    apt: update_cache=yes

  - name: Install Server Basics
    apt: pkg='{{ item }}' state=installed
    with_flattened: 
    - '{{ install_pkgs }}'
    - '{{ install_pkgs_distribution }}'
    - '{{ install_pkgs_inventory_group }}'
    - '{{ install_pkgs_inventory_host }}'

  when: ansible_distribution in ['Debian', 'Ubuntu']

- block: 
  - name: Add EPEL repo
    yum: validate_certs=no name='https://dl.fedoraproject.org/pub/epel/7/x86_64/e/epel-release-7-8.noarch.rpm'

  - name: disable delta rpms
    lineinfile: dest='/etc/yum.conf' line='deltarpm=0' insertafter='\[main\].*' regexp='^deltarpm.*' backup=yes

  - name: Configure sources
    template: src='yum.repos.d/{{ ansible_distribution }}-Base.repo' dest=/etc/yum.repos.d/ backup=yes

  - name: YUM Cache Update
    yum: name='*' state=latest update_cache=yes

  - name: Install Server Basics
    yum: name='{{ item }}' state=installed
    with_flattened: 
    - '{{ install_pkgs }}'
    - '{{ install_pkgs_distribution }}'

  when: ansible_distribution in ['RedHat', 'CentOS']

#- name: Add Periodic Configuration
#  copy: src=10periodic dest=/etc/apt/apt.conf.d/10periodic owner=root group=root

#- name: Add Unattended Upgrade Configuration
#  copy: src=50unattended-upgrades dest=/etc/apt/apt.conf.d/50unattended-upgrades owner=root group=root
#  notify:
#   - Restart Unattended Upgrades


