---
- name: Install LSB-Release
  apt: pkg=lsb-release state=installed

- name: Gather Facts
  setup:

- name: Configure sources.list
  template: src='apt/sources.list.{{ ansible_distribution }}' dest=/etc/apt/sources.list

- name: Debian Desktop Specific sources.list.d
  template: dest=/etc/apt/sources.list.d/ src=apt/sources.list.d/deb-multimedia.org.list
  when: '"desktops" in {{ group_names }} and ansible_distribution =="Debian" '

- name: APT Cache Update
  apt: update_cache=yes

- name: Install Server Basics
  apt: pkg={{ item }} state=installed
  with_items: install_pkgs

#- name: Add Periodic Configuration
#  copy: src=10periodic dest=/etc/apt/apt.conf.d/10periodic owner=root group=root

#- name: Add Unattended Upgrade Configuration
#  copy: src=50unattended-upgrades dest=/etc/apt/apt.conf.d/50unattended-upgrades owner=root group=root
#  notify:
#   - Restart Unattended Upgrades


