---
- name: Configure sources
  template: src='apt/sources.list.{{ ansible_distribution }}' dest=/etc/apt/sources.list backup=yes

- name: APT Cache Update
  apt: update_cache=yes
  changed_when: False

- name: Install Server Basics common
  apt: pkg="{{ common_install_pkgs }}"
- name: Install Server Basics distrib
  apt: pkg="{{ common_install_pkgs_distribution }}"
- name: Install Server Basics groups
  apt: name="{{ common_install_pkgs_groups[item] }}"
  loop: "{{ group_names }}"
  when: item in common_install_pkgs_groups
- name: Install Server Basics host-specific
  apt: name="{{ common_install_pkgs_host }}"
  when: common_install_pkgs_host is defined

#- name: Add Periodic Configuration
#  copy: src=10periodic dest=/etc/apt/apt.conf.d/10periodic owner=root group=root

#- name: Add Unattended Upgrade Configuration
#  copy: src=50unattended-upgrades dest=/etc/apt/apt.conf.d/50unattended-upgrades owner=root group=root
#  notify:
#   - Restart Unattended Upgrades
