---
# switched to gathering = smart in ansible.cfg
#- name: Gather Facts
#  setup:
#  tags: [install, basic, ssh, grub, rsyslog, pki]

- name: Include OS-specific variables
  include_vars: 'os_{{ ansible_os_family }}.yml'
  tags: [common_install, common_basic, common_ssh]

- import_tasks: install_Debian.yml
  when: ansible_os_family == 'Debian'
  tags: common_install

- import_tasks: install_RedHat.yml
  when: ansible_os_family == 'RedHat'
  tags: common_install

- import_tasks: basic.yml
  tags: common_basic

- import_tasks: ssh.yml
  tags: common_ssh

- import_tasks: snmp.yml
  when: snmp_community is defined
  tags: common_snmp

- import_tasks: postfix.yml
  when: 
  - "'mail_servers' not in group_names"
  tags: common_postfix
