---
- name: Gather Facts
  setup:
  tags: always
  when: ansible_distribution is not defined

- include_vars: 'os_{{ ansible_os_family }}.yml'
  tags: always

- include: 'install_{{ ansible_os_family }}.yml'
  tags: install

- include: basic.yml
  tags: basic

- include: sudo.yml
  tags: sudo

- include: ssh.yml
  tags: ssh

- include: snmp.yml
  when: snmp_community is defined
  tags: snmp

- include: postfix.yml
  when: 
  - "'mail_servers' not in group_names"
  - domain != 'private'
  tags: common:postfix
