---
- name: Gather Facts
  setup:
  tags: [install, basic, ssh, grub, rsyslog, pki]

- name: Include OS-specific variables
  include_vars: 'os_{{ ansible_os_family }}.yml'
  tags: [install, basic, ssh]

- include: 'install_Debian.yml'
  tags: install
  when: ansible_os_family == 'Debian'

- include: 'install_RedHat.yml'
  tags: install
  when: ansible_os_family == 'RedHat'

- include: basic.yml
  tags: basic

- include: sudo.yml
  tags: sudo

- include: ssh.yml
  tags: ssh

- include: snmp.yml
  when: snmp_community is defined
  tags: snmp

- include: postfix.yml
  when: 
  - "'mail_servers' not in group_names"
  tags: common:postfix
