---
# switched to gathering = smart inansible.cfg
#- name: Gather Facts
#  setup:
#  tags: [install, basic, ssh, grub, rsyslog, pki]

- name: Include OS-specific variables
  include_vars: 'os_{{ ansible_os_family }}.yml'
  tags: [common_install, common_basic, common_ssh]

- include_tasks: 'install_{{ ansible_os_family }}.yml'
  tags: common_install
  when: ansible_os_family in ['Debian', 'RedHat']

- import_tasks: basic.yml
  tags: common_basic

- include_tasks: sudo.yml
  tags: common_sudo

- include_tasks: ssh.yml
  tags: common_ssh

- include_tasks: snmp.yml
  when: snmp_community is defined
  tags: common_snmp

- include_tasks: postfix.yml
  when: 
  - "'mail_servers' not in group_names"
  tags: common_postfix
