---
- name: Gather Facts
  setup:
  tags: always
  when: ansible_distribution is not defined

- include_vars: '{{ item }}'
  with_first_found:
    - 'os_{{ ansible_os_family }}.yml'
    - os_default.yml
  tags: always

- include: install.yml
  tags: install

- include: basic.yml
  tags: basic

- include: sudo.yml
  tags: sudo

- include: ssh.yml
  tags: ssh

- include: snmp.yml
  when: snmp_community is defined
  tags: snmp

- include: postfix.yml
  when:
  - '"mail_servers" not in {{ group_names }}'
  - domain != 'private'
  tags: postfix
