---
- name: Create SSH Keys Dir
  file: dest=/etc/ssh/keys/ state=directory

- name: SSH Copy Root Key
  copy: dest=/etc/ssh/keys/root content='{{ root_pubkey }}@{{ domain }}\n'

- name: SSH Server Config File
  template: src=ssh/sshd_config dest=/etc/ssh/sshd_config validate='sshd -t -f %s' backup=yes
  notify: restart ssh
  
  #- name: SSH Service Config
  #file: dest=/etc/systemd/system/sshd.service.d/ state=directory
  #tags: this

  #- name: SSH Service Config
  #template: src=systemd/system/sshd.service.d/ansible.conf dest=/etc/systemd/system/sshd.service.d/
  #notify:
    #- systemd reload
    #- restart ssh

- name: SSH Client Config File
  template: src=ssh/ssh_config dest=/etc/ssh/ssh_config
  tags: this
