---
- name: Gather Facts
  setup:

- name: Create SSH Keys Dir
  file: dest=/etc/ssh/keys/ state=directory

- name: SSH Copy Root Key
  template: dest=/etc/ssh/keys/root src=ssh/keys/root

- name: SSH Server Config File
  template: src=ssh/sshd_config dest=/etc/ssh/sshd_config validate='sshd -t -f %s'
  notify: restart ssh

- name: SSH Client Config File
  template: src=ssh/ssh_config dest=/etc/ssh/ssh_config
