---
dependencies:
- role: mysql
  tags: [deps, mysql]
- role: debops.nginx
  tags: [deps, nginx]
  nginx__dependent_servers:
  - name: '{{ mail_server_name }}'
    root: '{{ roundcube_path }}'
    enabled: True
    ssl: True
    welcome: False
    type: php
    php_upstream: 'unix:/var/run/php/php7.0-fpm.sock'
    php_options: |
      location ~* /admin/(.*)$ {
      alias /usr/share/postfixadmin/$1;
      fastcgi_pass unix:/var/run/php/php7.0-fpm.sock;
      allow 127.0.0.1;
      allow 10.0.0.0/8;
      allow 192.168.0.0/16;
      allow 62.117.122.2;
      deny all;
      }
