# Kickstart for CentOS 6.6, Asterisk 13 Advanced
# platform=x86, AMD64, or Intel EM64T
# version=DEVEL
# Firewall configuration
firewall --disabled
# Install OS instead of upgrade
install
# Use network installation
url --url="{{ centos.mirror_url}}/{{ centos.ver }}/os/{{ centos.arch }}/"
# Root password
rootpw --iscrypted {{ root_password }}
# System authorization information
auth  --useshadow
# Use graphical install
graphical
firstboot --disable
# System keyboard
keyboard us
# System language
lang en_US
# SELinux configuration
selinux --disabled
# Installation logging level
logging --level=info
# System timezone change as appropriate before running ks
timezone {{ timezone }}
# Reboot after installation
reboot
# Change to 1024x768 if you have issues - 1920x1080 works for 23 inch monitors
# xconfig --resolution 1920x1080 --depth 16 --startxonboot  --defaultdesktop gnome
# Network information - device=em1 in CentOS 6 unless /tftpboot/pxe/pxelinux.cfg kernel boot options set with biosdevname=0
network  --bootproto=dhcp --device=eth0 --onboot=on
# System bootloader configuration
bootloader --location=mbr
# Clear the Master Boot Record
zerombr
# Partition clearing information
clearpart --all  
# Disk partitioning information
part / --fstype="ext4" --grow --size=1

# packages and dependencies for CentOS 6 and Asterisk
%packages
# use --resolvedeps if not working but CentOS 6 will resolve if needed on ks
@base
@compat-libraries
@console-internet
@debugging
@development
@fonts
@network-tools
@server-platform
@system-admin-tools
@web-server
libcap-devel
libical-devel
libogg-devel
libtermcap-devel
libtool-ltdl-devel
libuuid-devel
libvorbis-devel
lua-devel
ncurses-devel
neon-devel
php-devel
popt-devel
setroubleshoot
speex-devel
unixODBC-devel
