---
- name: install bind packages
  apt: pkg={{ bind_pkgs }} state={{ bind_pkg_state }} update_cache=yes
  tags: package

- name: create slave zones path
  file: dest={{ bind_slavezones_path }} state=directory owner={{ bind_user }} group={{ bind_group }} mode=0755
  when: bind_config_slave_zones|bool
  tags: bindconf

- name: create master zones path
  file: dest={{ bind_masterzones_path }} state=directory owner={{ bind_user }} group={{ bind_group }} mode=0755
  when: bind_config_master_zones|bool
  tags: bindconf
  register: masterzones_path_create

- synchronize:
    mode: push
    src: '{{ inventory_dir }}/backup/{{ inventory_hostname }}/masters/'
    dest: '{{ bind_masterzones_path }}'
    archive: no
    recursive: yes
    times: yes
    delete: no
    rsync_opts: ['--update']
  when: masterzones_path_create.changed
  ignore_errors: True
  tags: bindconf


- name: setup log directory
  file: dest={{ bind_log_path }} state=directory owner={{ bind_user }} group={{ bind_group }}
  notify: restart bind
  tags: bindconf

- name: setup config files
  template: src={{ item }} dest={{ bind_config_basepath }}/{{ item }} owner={{ bind_user }} group={{ bind_group }} mode=0600 backup=yes
  with_items:
  - named.conf.local.master
  - named.conf.local.slave
  - named.conf.local.forward
  - named.conf.options
  - named.conf.local
  - named.conf
  notify: check and restart bind
  tags: bindconf

- name: start/stop bind service
  service: name={{ bind_service_name }} state={{ bind_service_state }} enabled={{ bind_service_enabled }}
  tags: service
