---
- name: install bind packages
  apt: pkg={{ item }} state={{ bind_pkg_state }}
  with_items: '{{ bind_pkgs }}'
  tags: package

- name: create slave zones path
  file: dest={{ bind_slavezones_path }} state=directory owner={{ bind_user }} group={{ bind_group }} mode=0755
  when: bind_config_slave_zones
  tags: bindconf

- name: create master zones path
  file: dest={{ bind_masterzones_path }} state=directory owner={{ bind_user }} group={{ bind_group }} mode=0755
  when: bind_config_master_zones
  tags: bindconf
  register: masterzones_path_create

- synchronize:
    mode: push
    src: '{{ inventory_dir }}/backup/{{ inventory_hostname }}/masters/'
    dest: '{{ bind_masterzones_path }}'
    archive: no
    recursive: yes
    times: yes
    delete: no
    rsync_opts: ['--update']
  when: masterzones_path_create.changed
  ignore_errors: True
  tags: bindconf


- name: setup log directory
  file: dest={{ bind_log_path }} state=directory owner={{ bind_user }} group={{ bind_group }}
  notify: restart bind
  tags: bindconf

- name: setup zones
  template: src=named.conf.local.{{ item }}.j2 dest={{ bind_config_basepath }}/named.conf.local.{{ item }} owner={{ bind_user }} group={{ bind_group }} mode=0600 backup=yes
  with_items:
  - master
  - slave
  - forward
  notify: reload bind
  tags: bindconf

- name: configure bind options
  template: src=named.conf.options.j2 dest={{ bind_config_basepath }}/named.conf.options owner={{ bind_user }} group={{ bind_group }} mode=0600 backup=yes
  notify: restart bind
  tags: bindconf

- name: configure bind
  copy: src=named.conf dest={{ bind_config_basepath }}/named.conf owner={{ bind_user }} group={{ bind_group }} mode=0600 validate='named-checkconf %s'
  notify: restart bind
  tags: bindconf

- name: start/stop bind service
  service: name={{ bind_service_name }} state={{ bind_service_state }} enabled={{ bind_service_enabled }}
  tags: service
