---
- name: Include Distribution version specific variables
  include_vars: "{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml"
  tags: [postfix, dovecot, roundcube, pfa, fail2ban]

- apt: state=installed pkg={{ item }}
  with_items: '{{ mail_server_pkgs }}'
 
#- copy: dest=/etc/ssl/private/ src="{{ inventory_dir }}/files/{{ mail_server_name }}.pem" owner=root group=ssl-cert mode=0640

- user: name=www-data groups=ssl-cert append=yes
- user: name=dovecot groups=ssl-cert append=yes
- user: name=postfix groups=ssl-cert append=yes

- lineinfile: dest=/etc/hosts regexp='127.0.0.1 {{ mail_server_name }}' line='127.0.0.1 {{ mail_server_name }}'
  when:  ansible_ssh_host != mail_server_name

- lineinfile: dest=/etc/rsyslog.conf regexp='.*/var/log/syslog.*' line='*.*;auth,authpriv,mail.none -/var/log/syslog'
  notify: Restart rsyslog
- lineinfile: dest=/etc/rsyslog.conf regexp='^mail.*' state=absent
  notify: Restart rsyslog
- file: dest="{{ mail_log_dir }}" state=directory owner=root group=adm mode=0755
- template: dest=/etc/logrotate.d/ src=logrotate.d/mail_server
- template: dest=/etc/rsyslog.d/ src=rsyslog.d/mail_server.conf
  notify: Restart rsyslog

- name: configure postgrey options
  lineinfile: dest=/etc/default/postgrey regexp='^POSTGREY_OPTS.*' line='POSTGREY_OPTS="--inet=127.0.0.1:10023 --max-age=360"'

- template: dest=/etc/spamassassin/ src=spamassassin/local.cf backup=yes
  notify: Reload spamassassin
  tags: spamass

- name: configure spamassassin options
  lineinfile: dest=/etc/default/spamassassin regexp='^OPTIONS.*' line='OPTIONS="--create-prefs --max-children 10 --helper-home-dir -u debian-spamd"'
  notify: Reload spamassassin
  tags: spamass

- name: configure spamass-multer options
  lineinfile: dest=/etc/default/spamass-milter regexp='^OPTIONS.*' line='OPTIONS="-u debian-spamd -i 127.0.0.1"'
  tags: spamass

- import_tasks: postfix.yml
  tags: postfix

- import_tasks: dovecot.yml
  tags: dovecot
 
- import_tasks: roundcube.yml
  tags: roundcube
  
- import_tasks: pfa.yml
  tags: pfa

- template: dest=/etc/fail2ban/ src=fail2ban/fail2ban.local
  tags: fail2ban
  notify: Restart fail2ban
- template: dest=/etc/fail2ban/ src=fail2ban/jail.local
  tags: fail2ban
  notify: Restart fail2ban
- template: dest=/etc/fail2ban/filter.d/ src=fail2ban/filter.d/roundcube.conf
  tags: fail2ban
  notify: Restart fail2ban

- name: enable and start postgrey
  service: name=postgrey state=started enabled=yes

- name: enable spamassassin
  service: name=spamassassin enabled=yes
  tags: spamass

- name: start spamassassin
  service: name=spamassassin state=started
  tags: spamass

- name: enable spamass-milter (remake to a systemd script)
  file: src=/etc/init.d/spamass-milter dest=/etc/rc2.d/S50spamass-milter state=link
  tags: spamass

