---
- apt: state=installed pkg={{ item }}
  with_items: '{{ mail_server_pkgs }}'
 
- copy: dest=/etc/ssl/private/ src=files/{{ mail_server_name }}.pem owner=root group=ssl-cert mode=0640

- lineinfile: dest=/etc/rsyslog.conf regexp='.*/var/log/syslog.*' line='*.*;auth,authpriv,mail.none -/var/log/syslog'
  notify: Restart rsyslog

- name: configure postgrey
  lineinfile: dest=/etc/default/postgrey regexp='^POSTGREY_OPTS.*' line='POSTGREY_OPTS="--inet=127.0.0.1:10023 --max-age=360"'

- name: enable and start postgrey
  service: name=postgrey state=started enabled=yes
  
- include: postfix.yml
  tags: postfix

- include: dovecot.yml
  tags: dovecot
 
- include: roundcube.yml
  tags: roundcube
  
- include: pfa.yml
  tags: pfa

- template: dest=/etc/fail2ban/ src=fail2ban/fail2ban.local
  notify: Restart fail2ban
- template: dest=/etc/fail2ban/ src=fail2ban/jail.local
  notify: Restart fail2ban
- template: dest=/etc/fail2ban/filter.d/ src=fail2ban/filter.d/roundcube.conf
  notify: Restart fail2ban
