---
#- get_url: dest=/tmp/postfixadmin.tgz url=https://sourceforge.net/projects/postfixadmin/files/latest/download
#- file: dest=/opt/postfixadmin state=directory
#- unarchive: dest=/opt/postfixadmin src=/tmp/postfixadmin.tgz copy=no

- get_url: dest=~/ url="http://downloads.sourceforge.net/project/postfixadmin/postfixadmin/postfixadmin-{{ postfixadmin_version }}/postfixadmin_{{ postfixadmin_version }}-1_all.deb"

- apt: deb="~/postfixadmin_{{ postfixadmin_version }}-1_all.deb"
  ignore_errors: true

- template: dest=/etc/postfixadmin/ src=postfixadmin/config.local.php backup=yes

- template: dest=/etc/postfixadmin/ src=postfixadmin/postfixadmin-mailbox-postdeletion.sh mode=0755

- template: dest=/etc/sudoers.d/  src=sudoers.d/mail_server mode=0640

- file: dest=/usr/share/postfixadmin/templates_c owner=www-data
