---
- git: dest={{ roundcube_path }} repo=https://github.com/roundcube/roundcubemail.git version=release-{{ roundcube_version }} force=no update={{roundcube_update | d('yes') }}

- command: ./bin/install-jsdeps.sh chdir={{ roundcube_path }} creates=program/js/jquery.min.js
  when:
  - roundcube_version | version_compare('1.3', '>=')

- mysql_db: name={{ roundcube_db_name }}  encoding=utf8 collation=utf8_bin
  register: roundcube_db_state

- mysql_db: name={{ roundcube_db_name }} state=import target='{{ roundcube_path }}/SQL/mysql.initial.sql'
  when: roundcube_db_state.changed

- mysql_user: name={{ roundcube_db_user }} password={{ roundcube_db_password }} priv='{{ roundcube_db_name }}.*:ALL'

- template: dest={{ roundcube_path}}/config/config.inc.php src=roundcube/config.inc.php backup=yes

- template: dest={{ roundcube_path}}/plugins/additional_message_headers/config.inc.php src=roundcube/additional_message_headers.config.inc.php backup=yes

#- template: dest=/etc/nginx/sites-enabled/default src=roundcube/nginx.conf backup=yes
#  notify: Restart nginx

- patch: basedir={{ roundcube_path }} src=templates/roundcube/patch1.patch strip=0

- lineinfile: dest={{ php_fpm_path }} regexp='^upload_max_filesize.*' line='upload_max_filesize = 21M'
  tags: phpfpm
- lineinfile: dest={{ php_fpm_path }} regexp='^post_max_size.*' line='post_max_size = 21M'
  tags: phpfpm
